# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='synchro',
  syntax='proto3',
  serialized_pb=_b('\n\rmessage.proto\x12\x07synchro\"\xb8\x01\n\x0eSynchroMessage\x12\x11\n\tprocessID\x18\x01 \x01(\x05\x12\r\n\x05\x63lock\x18\x02 \x03(\x05\x12\x31\n\x04type\x18\x03 \x01(\x0e\x32#.synchro.SynchroMessage.MessageType\x12\x10\n\x08objectID\x18\x04 \x01(\t\"?\n\x0bMessageType\x12\x08\n\x04LOCK\x10\x00\x12\n\n\x06UNLOCK\x10\x01\x12\n\n\x06NOTIFY\x10\x02\x12\x0e\n\nNOTIFY_ALL\x10\x03\"4\n\x12InitRequestMessage\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05ready\x18\x02 \x01(\x08\"V\n\x13InitResponseMessage\x12\x11\n\tprocessID\x18\x01 \x01(\x05\x12\x19\n\x11portMapperAddress\x18\x02 \x01(\t\x12\x11\n\taddresses\x18\x03 \x03(\t\"\'\n\x14NewConnectionMessage\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SYNCHROMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='synchro.SynchroMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOCK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNLOCK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTIFY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTIFY_ALL', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=148,
  serialized_end=211,
)
_sym_db.RegisterEnumDescriptor(_SYNCHROMESSAGE_MESSAGETYPE)


_SYNCHROMESSAGE = _descriptor.Descriptor(
  name='SynchroMessage',
  full_name='synchro.SynchroMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='processID', full_name='synchro.SynchroMessage.processID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clock', full_name='synchro.SynchroMessage.clock', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='synchro.SynchroMessage.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='objectID', full_name='synchro.SynchroMessage.objectID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYNCHROMESSAGE_MESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=211,
)


_INITREQUESTMESSAGE = _descriptor.Descriptor(
  name='InitRequestMessage',
  full_name='synchro.InitRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='synchro.InitRequestMessage.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ready', full_name='synchro.InitRequestMessage.ready', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=265,
)


_INITRESPONSEMESSAGE = _descriptor.Descriptor(
  name='InitResponseMessage',
  full_name='synchro.InitResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='processID', full_name='synchro.InitResponseMessage.processID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='portMapperAddress', full_name='synchro.InitResponseMessage.portMapperAddress', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='synchro.InitResponseMessage.addresses', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=353,
)


_NEWCONNECTIONMESSAGE = _descriptor.Descriptor(
  name='NewConnectionMessage',
  full_name='synchro.NewConnectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='synchro.NewConnectionMessage.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=394,
)

_SYNCHROMESSAGE.fields_by_name['type'].enum_type = _SYNCHROMESSAGE_MESSAGETYPE
_SYNCHROMESSAGE_MESSAGETYPE.containing_type = _SYNCHROMESSAGE
DESCRIPTOR.message_types_by_name['SynchroMessage'] = _SYNCHROMESSAGE
DESCRIPTOR.message_types_by_name['InitRequestMessage'] = _INITREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['InitResponseMessage'] = _INITRESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['NewConnectionMessage'] = _NEWCONNECTIONMESSAGE

SynchroMessage = _reflection.GeneratedProtocolMessageType('SynchroMessage', (_message.Message,), dict(
  DESCRIPTOR = _SYNCHROMESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:synchro.SynchroMessage)
  ))
_sym_db.RegisterMessage(SynchroMessage)

InitRequestMessage = _reflection.GeneratedProtocolMessageType('InitRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _INITREQUESTMESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:synchro.InitRequestMessage)
  ))
_sym_db.RegisterMessage(InitRequestMessage)

InitResponseMessage = _reflection.GeneratedProtocolMessageType('InitResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _INITRESPONSEMESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:synchro.InitResponseMessage)
  ))
_sym_db.RegisterMessage(InitResponseMessage)

NewConnectionMessage = _reflection.GeneratedProtocolMessageType('NewConnectionMessage', (_message.Message,), dict(
  DESCRIPTOR = _NEWCONNECTIONMESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:synchro.NewConnectionMessage)
  ))
_sym_db.RegisterMessage(NewConnectionMessage)


# @@protoc_insertion_point(module_scope)
